### PR TITLE
Merged master with timetable

### PR DESCRIPTION
**Pull request by foreverwander**
1. timetable now up to date with master, conflicts have been resolved

2. removed all css from js files, now just classes and hs files to generate css instead

3. manualTutorial/Practical enrolment has not been fixed yet (still works for courses with only tutorials, or tutorials and practicals, courses with only practicals cannot load at the moment)

### CODE REVIEW

**Comment by david-yz-liu** [comment]
@foreverwander I merged in @shaftoes's work for manualPracticalEnrolment

**Comment by foreverwander** [comment]
@david-yz-liu  Thank you! Would you like my next pull request to be to half-hour or to master?

**Comment by david-yz-liu** [comment]
Do the half-hour tutorials and labs both work now?

**Comment by foreverwander** [comment]
not yet. I just saw this right now. I have to go and clean up the code this afternoon. but I'm just wondering where i should submit a pull request after i do that.

**Comment by david-yz-liu** [comment]
half-hour, then

**Pull request merged**
