### PR TITLE
Convert graph scripts to ES6 via webpack+babel

### PR DESCRIPTION
**Pull request by elliottsj**
All of the changes in this PR are a conversion of the **existing code** for the `/graph` page from an ad-hoc sequence of `<script src="..."></script>`s to a webpack bundle (with [ES6](https://github.com/lukehoban/es6features) support).

[Conversion of the graph view to React](https://github.com/Courseography/courseography/issues/569) will be an extension of this branch.

### CODE REVIEW

**Comment by david-yz-liu** [comment]
I'm not sure the `.editorconfig` belongs in here.

**Comment by elliottsj** [comment]
@david-yz-liu: True; that should probably be a separate PR

**Comment by elliottsj** [comment]
@david-yz-liu: Ok, I've rebased and deleted that commit.

**Comment by david-yz-liu** [comment]
@elliottsj Looks like the rebase is confusing Github. Can you do a merge?

**Comment by elliottsj** [comment]
I think react-graph needs to be updated with master: #588

**Comment by david-yz-liu** [comment]
It seems that was not the issue.

**Comment by elliottsj** [comment]
@david-yz-liu: Alright, a couple merges seems to fix it.

**Comment by david-yz-liu** [comment]
It seems you added logging; I would appreciate if you made the same pull request into the master branch, so I can get someone to build on that.

**Pull request merged**
