### PR TITLE
Privacy Policy

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
This pull request adds in the initial privacy policy.

### CODE REVIEW

**Comment by david-yz-liu** [comment]
Thanks for getting started on this, @Ian-Stewart-Binks. Only one comment right now - I don't think it should be a separate tab on the Nav bar. Link to it at the bottom of the About page.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu I've added it to the README and removed it from MasterTemplate. Perhaps we should consider having a footer and add the Privacy Policy link to that, just like how GitHub has privacy in their footer.

**Comment by david-yz-liu** [comment]
Thanks, @Ian-Stewart-Binks. Our current footer *certainly* can be improved.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I put in an amended, shorter privacy policy.

**Pull request merged**
