### PR TITLE
Remove unused image assets and update others

### PR DESCRIPTION
**Pull request by arkon**

### CODE REVIEW

**Comment by david-yz-liu** [comment]
I would like to start using the checkmark again at some point in the near future; would you mind keeping that one in there, or perhaps replacing it with a nicer-looking one?

**Comment by arkon** [comment]
@david-yz-liu Added a checkmark icon.

**Comment by david-yz-liu** [comment]
Thanks @arkon. FYI, you'd accidentally committed the `courseography` binary; I removed it when merging. This is more impetus to fix the dumb relative paths in the current build process.

**Comment by arkon** [comment]
@david-yz-liu Whoops, didn't notice that I accidentally added that file.

**Pull request merged**
