### PR TITLE
Styling for privacy page

### LINKED ISSUE #609: Make the Privacy page have the same styling as the About page

### PR DESCRIPTION
**Pull request by cchens**
Resolves #609

### CODE REVIEW

**Comment by arkon** [comment]
Seems like the commits you had for #615 snuck into this PR too.

**Comment by christinem** [comment]
@cchens when making pull requests, try to put the branch number in the commit message at the beginning as well as it says here, https://github.com/Courseography/courseography/wiki/Commit-Style-Guide :) And then if you're building on top of a branch that hasn't been committed yet, just make a reference to it in the PR comment so @david-yz-liu knows to merge in that one first so that the diff for the current one is easier to read!

**Comment by cchens** [comment]
@christinem I totally did not include the other branch on purpose :|

**Comment by christinem** [comment]
@cchens Ahhhh I see. Not a problem! If you ever do though, then that's a way too. And the branch names on the commit messages help with that too,

**Comment by cchens** [comment]
See PR #617

**Pull request closed without merging**
