### PR TITLE
Haskell Directory Structure

### LINKED ISSUE #377: Directory Structre: HS directory
The hs directory structure needs to be improved.

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
I have improved the directory structure of the hs directory. I still think that it can be improved further, but this is a good first step.

Fixes #377

Note that some things have been cleaned up as well, `post` is removed from server.hs, and `import SVGGen` statements have been removed.

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Response directory has been removed.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks I think I was wrong about getting rid of the `Response` directory. I can't recall why I wanted to do that. If you happen to remember, please let me know - I'm working on recreating that directory now.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu I have a faint memory of it. I believe you wanted to group the responses with their corresponding models and views, or something like that. My apologies, the memory is not so clear.

**Comment by david-yz-liu** [comment]
Ah you're right. I admire the intent, but some of the smaller responses seem too trivial to separate. I'll think more on this.

**Pull request merged**
