### PR TITLE
build: enable webpack production mode by default

### PR DESCRIPTION
**Pull request by modderme123**
## Motivation and Context

Building in production enables some optimizations in React and ships a significantly smaller js bundle to users. However, this comes at the tradeoff of worse debugability and slower compile times (40s vs 1s), so should only be used for production. Thus we split the server into two modes: development (`stack run dev-server`) and production (`stack run server`)

## Your Changes

**Description**:
In this PR we allow for running a custom client build command when we run the server. This allows us to swap in production and development commands.

We then add a `dev-server` command for running webpack in dev and watch mode locally, and make the default `server` run `yarn run build` instead of `yarn run watch` (organized this way so that the production server doesn't have to change the run command)

**Type of change** (select all that apply):

- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring (internal change to codebase, without changing functionality)
- [x] Documentation update (change that modifies or updates documentation)

## Testing

`stack test` and `yarn test` and quick visual testing in the browser.

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have verified that the CircleCI tests have passed.

### CODE REVIEW

**Review by david-yz-liu — COMMENTED** [review]
@modderme123 thank you! My main comment is that I want the default to still be the development server, so please swap to `stack run server` and `stack run prod-server`

**Comment by modderme123** [comment]
Updated! Looks like CircleCI is failing because the `sudo` command is not found...

**Review by david-yz-liu — APPROVED** [review]

**Comment by david-yz-liu** [comment]
Thank you @modderme123, indeed it looks like the docker image we were using for CircleCI was updated 2 days ago (https://hub.docker.com/r/fpco/stack-build/)!

**Comment by modderme123** [comment]
Neat, thanks!

**Pull request merged**
