### PR TITLE
Edge tests

### PR DESCRIPTION
**Pull request by Fullchee**
Why this PR
-------------------------
Test the functionality of edge tests

Breakdown of Tests
--------------------
1. Behaviour of edges when relevant nodes are clicked
2. Behaviour of edges when relevant nodes are hovered over
   a. hovering over the source node
   b. hovering over the destination node

### CODE REVIEW

**Comment by Fullchee** [comment]
Forced pushed to remove whitespace

**Comment by Fullchee** [comment]
Failing because of stack dependencies.

I'll make a PR with the action recommended by CircleCI.

**Comment by david-yz-liu** [comment]
@Fullchee can you rebase this off of master now?

**Comment by Fullchee** [comment]
Rebased to master!

**Pull request merged**
