### PR TITLE
Merge Master -> React Post

### PR DESCRIPTION
**Pull request by christinem**

### CODE REVIEW

**Comment by david-yz-liu** [comment]
Don't include the `hs/dist` folder

**Comment by christinem** [comment]
@david-yz-liu Done. I also added /hs/dist/ to the .gitignore file - let me know whether that is okay.

**Comment by david-yz-liu** [comment]
That folder shouldn't be there anymore; it's a holdover from using cabal, I believe. Don't change the .gitignore, you should be able to delete the folder entirely.

**Comment by christinem** [comment]
@david-yz-liu Ah, my mistake. I changed the .gitignore back, and the folder is now removed.

**Comment by david-yz-liu** [comment]
I didn't test this out, but I will tomorrow. If it all looks good, I'll merge it into master as well!

**Pull request merged**
