### PR TITLE
Conflict dialog fades after 3 seconds

### LINKED ISSUE #724: Grid conflict overlay blocks search box
When conflicting courses are selected in the grid, the warning overlay prevents the user from searching for more courses until one of the conflicting courses is removed.

### PR DESCRIPTION
**Pull request by pkukulak**
This fixes #724 .

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
I would be cool scrapping it. What are your thoughts @pkukulak?

**Comment by pkukulak** [comment]
I kind of agree. It's always nice to have a "don't tell us we didn't say so" disclaimer, but the red cells are already enough of an indication that there's a conflict. Reducing clutter is always a good thing.

**Comment by Ian-Stewart-Binks** [comment]
Yeah, I think that the red cells probably do the job. Clutter reduction would be nice.

**Comment by david-yz-liu** [comment]
Thanks, @pkukulak. I agree with the discussion here, and removed the conflict dialog.

**Pull request merged**
