### PR TITLE
Changed units mm to px - Parsing Error

### PR DESCRIPTION
**Pull request by tamaralipowski**
Graph parses correctly, but font appears black.
I have:
Checked for invisible rectangles
Checked for flowRoots
Checked for transform errors
Tried different positions for text with relation to nodes
Converted all text objects correctly

### CODE REVIEW

**Comment by david-yz-liu** [comment]
@tamaralipowski I have no idea about this one, sorry. However, I think you can fix the problem by deleting the texts which don't have a colour, copy-and-pasting one of the good texts, and re-constructing the deleted texts. Maybe do that one at a time.

**Comment by david-yz-liu** [comment]
@tamaralipowski are you planning on doing this?

**Comment by tamaralipowski** [comment]
@david-yz-liu Yep! Midterms will be done tomorrow morning.

**Comment by david-yz-liu** [comment]
Okay thanks!

**Comment by david-yz-liu** [comment]
Thanks, @tamaralipowski!

**Pull request merged**
