### PR TITLE
Timetable Info modal

### PR DESCRIPTION
**Pull request by david-yz-liu**
@Ian-Stewart-Binks @christinem 

I was clearly wrong about the Info button (#436) - I don't think it ever worked on master, as Muna did not submit a pull request with her changes. I just did it quickly here.

I've also provided a hotfix for the invalid timetable ids (#443), but this should be better worked out in the future. Seems to be working for now, though.

The query string change was unnecessary, as I had already changed the function in `CourseQueries.hs`. I'm undecided if it is better to change it there or in the Javascript. There was an issue, however, in appending one too many "H1"s to the string (see files changed).

Please let me know if you have any comments or questions.

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
For #436, Info modal doesn't work for the graph right now due to the IDs being lowercase.

**Comment by david-yz-liu** [comment]
I'll put back in that blank line, but the Info modal is working just fine for me... do you not have the latest `CourseQueries`?

**Comment by Ian-Stewart-Binks** [comment]
Ah, there we go.

**Comment by christinem** [comment]
Works for me too. Although the course names in the modal are now lowercase - I'm guessing because of the cookie change?

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks #443 is still open, if you want to work on it.

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu I hadn't requested to work on it, but sure.

**Comment by david-yz-liu** [comment]
@Ian-Stewart-Binks You don't have to!

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu It's okay, I'm good to take it on.

**Pull request merged**
