### PR TITLE
Add fb login button

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
This pull request adds in the Facebook 'login' button. The button is added in `MasterTemplate.hs`, so it can be accessed in both the Grid and in the Graph.

When a user is logged in, there name is retrieved from Facebook and added to the navigation bar. This is just meant to be an exercise in using the API through JavaScript.

When a user is logged in, they then are given the option to 'log out'.

I have also been playing around with the `fb` Haskell bindings. I can't find a good way to implement the 'log in' button with `fb` yet, there might not be one. I am still playing around with it, though.

Please try this out on your own machine, and let me know if it works.

Note that the App ID is fine to publish on GitHub. The App Secret is what we need to lock up.

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
One thing I'm not too pleased with is the lag in the setup of the login button, and in removing the username from the nav bar. In future pull requests I will try to make this faster.

**Comment by david-yz-liu** [comment]
Got this message: 

```
App Not Setup: The developers of this app have not set up this app properly for Facebook Login.
```

BTW, please add me as a developer of this app.

**Comment by Ian-Stewart-Binks** [comment]
I have added you as an administrator.

Do you still receive the message? I'm using a test app.

**Comment by david-yz-liu** [comment]
Yep, it works! How exciting!

**Comment by Ian-Stewart-Binks** [comment]
I know, right! Thanks!

**Pull request merged**
