### PR TITLE
Remove post.js from Scripts.hs

### PR DESCRIPTION
**Pull request by christinem**
This also fixes Issue #413.

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
There might be some global variables that no longer need to live.

**Comment by christinem** [comment]
Alright, I'll scour around the code and look for any.

**Comment by christinem** [comment]
I think I've now caught all the now-unneeded variables and references to functions in post.js.

**Comment by Ian-Stewart-Binks** [comment]
Good job on finding the mass of global variables in setup.js.

**Pull request merged**
