### PR TITLE
rm-utilities: Remove utilities directory.

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
Remove the utilities directory as decided in #190.

### CODE REVIEW

**Comment by david-yz-liu** [comment]
Thanks, @Ian-Stewart-Binks

**Comment by Ian-Stewart-Binks** [comment]
@david-yz-liu Not a problem. Should I remove the old code that would parse the JSON files? (Such as the FromJSON implementations in Tables.hs)?

**Comment by david-yz-liu** [comment]
Hmmm, we want the FromJSON and ToJSON implementations to match up. If there was a specific FromJSON implementation that was specifically for the old JSON files, and this doesn't match the ToJSON, then it would be best to change it.

**Comment by Ian-Stewart-Binks** [comment]
There's quite a bit of code that was used to parse the JSON files that were created from the web_parsing code. This code isn't needed any longer, which includes the FromJSON implementations.

**Comment by david-yz-liu** [comment]
Okay, then feel free to remove it.

**Pull request merged**
